[book]
title = "API mock (apimock-rs) Docs"
authors = ["nabbisen<nabbisen@scqr.net>"]
description = "API mock (apimock-rs) Docs: A developer-friendly, robust and functional HTTP mock server built in Rust."

language = "en"
multilingual = false

src = "."

[build]
build-dir = ".book"

# mermaid extension
[preprocessor.mermaid]
command = "mdbook-mermaid"
[output.html]
additional-js = [".mdbook/mermaid.min.js", ".mdbook/mermaid-init.js"]

# general [output.html]
git-repository-url = "https://github.com/apimokka/apimock-rs"
edit-url-template = "https://github.com/apimokka/apimock-rs/edit/main/docs/{path}"
